[package]
org = "ballerinax"
name = "aws.ses"
version = "1.0.0-SNAPSHOT"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["communication/email", "cost/freemium", "vendor/amazon"]
repository = "https://github.com/ballerina-platform/module-ballerinax-aws.ses"

[build-options]
observabilityIncluded = true
