name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Ballerina Build
        uses: ballerina-platform/ballerina-action/@nightly
        with:
          args: pack ./ses
      - name: Ballerina Test
        uses: ballerina-platform/ballerina-action/@nightly
        with:
          args: test --code-coverage ./ses
        env:
          ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          EMAIL_IDENTITY: ${{ secrets.EMAIL_IDENTITY }}

      # Read the ballerina test results
      - name: Read Ballerina Test Results
        id: test_results
        run: |
          content=`cat ./ses/target/report/test_results.json`                
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=testResultsJson::$content"

      # Print the code coverage information
      - name: Code Coverage
        run: |
          echo "Code Coverage Percentage : ${{fromJson(steps.test_results.outputs.testResultsJson).coveragePercentage}}"
          